proxy:
  #  代理配置
  #  国内墙了gpt的api，所以得用代理，一般你使用的代理软件会有相关信息，例子：
  #  host: 127.0.0.1
  #  port: 7890
  #  若不需要留空即可
  host:
  port:

gpt:
  # 使用的 chat 模型 如gpt-3.5-turbo/gpt-4 (https://platform.openai.com/docs/models/models)
  model: gpt-3.5-turbo
  # 最大token限制 越多的token意味着越多的花费(gpt-3.5-turbo上限为4096token, gpt-4则为8192)
  maxToken: 2048
  # 信息熵 越高回答越随机(Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.---via OPENAI)
  temperature: 0.5
  # 最大请求时间 超时自动中断请求
  ofSeconds: 10000
  # 基础提问 支持多个提问 可用来设定人格(对应api中的system角色)
  basicPrompt:
    - "用中文回答我的问题"
  #  openai的apikey
  #  支持多个key（虽然有判空，但仍然建议有多少个写多少个，别留空👨‍🔧）
  apiKey:
    -
qq:
  #  是否使用qq true/false
  enable: true
  #  qq账号
  account:
  #  是否自动同意好友申请
  acceptNewFriend: false
  #  是否自动同意被邀请入群
  acceptNewGroup: false
  #  ai画图时返回方法: true链接(更快) false图片
  returnDrawByURL: true

wechat:
  #  是否使用微信 true/false
  enable: false
  #  生成的登录二维码路径 默认与项目同级
  qrPath: "./"

keyword:
  #  重置会话指令
  reset: "重置会话"
  #  ai画图指令(DALL·E模型 https://platform.openai.com/docs/models/dall-e)
  #  generation 根据关键词生成图片(https://platform.openai.com/docs/guides/images/generations)
  draw: "ai画图"
